### ISSUE TITLE
Uncaught TypeError: Comp is not a function

### ISSUE THREAD

**Issue by jessybreyne** [solidjs/solid-router#212]
### Describe the bug

I followed the example of the doc. But the rooter does not work. I let you see the example on stackblitz. I have the following message in my console in the browser:
```
Uncaught TypeError: Comp is not a function
    at chunk-BMOKTV46.js?v=c0f3a5c4:560:12
    at untrack (chunk-BMOKTV46.js?v=c0f3a5c4:452:12)
    at Object.fn (chunk-BMOKTV46.js?v=c0f3a5c4:556:37)
    at runComputation (chunk-BMOKTV46.js?v=c0f3a5c4:753:22)
    at updateComputation (chunk-BMOKTV46.js?v=c0f3a5c4:738:3)
    at devComponent (chunk-BMOKTV46.js?v=c0f3a5c4:566:3)
    at createComponent (chunk-BMOKTV46.js?v=c0f3a5c4:1326:10)
    at shared.element.component.element.element [as outlet] (routing.js:52:21)
    at get children [as children] (components.jsx:57:68)
    at Object.fn (chunk-BMOKTV46.js?v=c0f3a5c4:1086:35)
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-bptwek?file=src/App.jsx

### Steps to Reproduce the Bug or Issue

1. Create a rooter like the doc in jsx
2. See the error in console

### Expected behavior

1. A router with routes, without error in console

### Platform

- OS: [Linux]
- Browser: [Brave]
- Version: [last]

**Comment by Brendan-csel** [comment]
Instead of `<Route path="/users" component={<div>Users</div>} />` ...

...do...
1. `<Route path="/about" element={<div>This site was made with Solid</div>} />`
2. or  `<Route path="/users" component={() => <div>Users</div>} />`
3. or  `<Route path="/users" component={Users} />` (and create a Users component)

There are examples of these on the router [readme page](https://github.com/solidjs/solid-router)
