### ISSUE TITLE
Not working in tagged template literals via CDN

### ISSUE THREAD

**Issue by itsumura-h** [solidjs/solid-router#236]
### Describe the bug

app.js
```js
import { render } from "https://cdn.skypack.dev/solid-js@1.6.10/web";
import html from "https://cdn.skypack.dev/solid-js@1.6.10/html";
import { Router, Routes, Route, A } from "https://cdn.skypack.dev/@solidjs/router@0.7.0";

function Page1(){
  return html`<h2>page1</h2>`
}

function Page2(){
  return html`<h2>page2</h2>`
}

function Page3(){
  return html`<h2>page3</h2>`
}

function Parent(){
  return html`
    <div>
      <${A} href="/">page1<//>
      <${A} href="/page2">page2<//>
      <${A} href="/page3">page3<//>
      <${Routes}>
        <!-- not working in every cases -->
        <${Route} path="/" element=${html`<p>page1</p>`} />
        <${Route} path="/page2" component=${()=>Page2} />
        <${Route} path="/page3" component=${Page3} />
      <//>
    </div>
  `
}

function App(){
  return html`
    <${Router}>
      <${Parent} />
    <//>
  `
}

render(App, document.getElementById('app'))
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script defer type="module" src="./app.js"></script>
  <title>Document</title>
</head>
<body>
  <div id="app"></div>
</body>
</html>
```

rendering is not changed or error raised.

I referenced this but couldn't fix.  
https://github.com/solidjs/solid-router/issues/212

### Your Example Website or App

https://stackblitz.com/edit/web-platform-bupxav?file=index.html

### Steps to Reproduce the Bug or Issue

1. open page in `/`, Page1 is rendered.
2. click link to Page2
3. rendering is not changed.

---

1. open page in `/`, Page1 is rendered.
2. click link to Page3
3. error railed.

```
Uncaught (in promise) TypeError: Comp is not a function
    at solid-9f0cc60a.js:1227:24
    at untrack (solid-9f0cc60a.js:427:12)
    at createComponent (solid-9f0cc60a.js:1227:10)
    at shared.element.component.element.element [as outlet] (router.js:351:32)
    at get children [as children] (router.js:781:22)
    at Object.fn (solid-9f0cc60a.js:1012:35)
    at runComputation (solid-9f0cc60a.js:676:22)
    at updateComputation (solid-9f0cc60a.js:659:3)
    at createMemo (solid-9f0cc60a.js:232:5)
    at children (solid-9f0cc60a.js:546:21)
```

### Expected behavior

Page1, Page2, Page3 is rendered

### Platform

- OS: [Linux]
- Browser: [Chrome, Brave]
- Version: [0.7]

**Comment by itsumura-h** [comment]
This was due to the CDN.
Changing the CDN solved the problem.

```js
import {
  createSignal,
  onCleanup,
} from "https://esm.sh/solid-js@1.6.11";
import {render} from "https://esm.sh/solid-js@1.6.11/web";
import { Router, Routes, Route, A } from "https://esm.sh/@solidjs/router@0.7.0?deps=solid-js@1.6.11";
import html from "https://esm.sh/solid-js@1.6.11/html";

function Page1(){
  return html`<h2>page1</h2>`
}

function Page2(){
  return html`<h2>page2</h2>`
}

function Page3(){
  return html`<h2>page3</h2>`
}

function App() {
  return html`
    <div>
      <${A} href="/">page1<//>
      <${A} href="/page2">page2<//>
      <${A} href="/page3">page3<//>
      <${Routes}>
        <${Route} path="/" component=${()=> Page1} />
        <${Route} path="/page2" component=${()=> Page2} />
        <${Route} path="/page3" component=${()=> Page3} />
      <//>
    </div>
  `;
}

render(()=>(
  html`
    <${Router}>
      <${App} />
    <//>
  `),
  document.getElementById('app')
);

```
