### ISSUE TITLE
router crash when used with Solid 1.7

### ISSUE THREAD

**Issue by amirzahavi** [solidjs/solid-router#261]
### Describe the bug

After upgrade to the latest version of `solidjs` and `@solidjs/router`, the router crashes with the following stack trace:
```
Uncaught TypeError: route.outlet is not a function
    at get children [as children] (components.jsx:65:68)
    at Object.fn (dev.js:994:35)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:678:3)
    at createMemo (dev.js:250:10)
    at children (dev.js:576:20)
    at dev.js:994:14
    at untrack (dev.js:434:12)
    at Object.fn (dev.js:990:36)
    at runComputation (dev.js:695:22)
 ```

As I understand Solid 1.7 introduce the ability for passing "child" signals without the `keyed` property in `Show` component

I think that the following commits will solve it, but I'm not sure if it is released or not:
- https://github.com/solidjs/solid-router/commit/a8a32b97ba47128f47e316455e65fde4b1c6f126
- https://github.com/solidjs/solid-router/commit/2212e2cd0f6d657c5f353dd2916c4526931d10cb

### Your Example Website or App

.

### Steps to Reproduce the Bug or Issue

example code:

```tsx
<Routes>
    <Route path="/home" element={<span>Hello</span>} />
    <Route path="*" element={<span>World</span>} />
</Routes>
```

### Expected behavior

As a user, i expected it to work 😝 

### Platform

- OS: macOS
- Browser: Chrome
- "solid-js": "^1.7.1"
- "@solidjs/router": "^0.7.1"

**Comment by amirzahavi** [comment]
My bad, I thought 0.71 is the latest, and it is currently 0.82
